import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import SessionWrapper from "./SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ecommerce Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-blue-900">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex`}>
        <SessionWrapper>
          <main className="bg-white flex-grow m-2 rounded-lg p-4">
            {children}
          </main>
        </SessionWrapper>
      </body>
    </html>
  );
}
